# Copyright (c) 2018 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Gopkg.toml
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

# This is hack to dep. Since dep follows semvar, which will eventually pull unexpected
# commit of coreos/bbolt, the compilation on linux system will not work without this. 
required = ["github.com/coreos/bbolt"]

[prune]
  unused-packages = true
  go-tests = true
  non-go = true

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.12.76"

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "3.3.13"

[[constraint]]
  name = "github.com/coreos/bbolt"
  version = "v1.3.1-coreos.6"
  
[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.3.0"

[[constraint]]
  name = "github.com/robfig/cron"
  revision = "2315d5715e36303a941d907f038da7f7c44c773b"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "github.com/Azure/azure-storage-blob-go"
  version = "0.3.0"

[[constraint]]
  name = "github.com/Azure/azure-pipeline-go"
  version = "v0.1.8"

[[constraint]]
  name = "cloud.google.com/go"
  version = "0.33.1"

[[constraint]]
  name = "github.com/googleapis/google-cloud-go-testing"
  revision = "f773598aef764db07257d386141bed45e60dc228"

[[constraint]]
  name = "github.com/gophercloud/gophercloud"
  revision = "c7ca48da8eafab13e1835090a1147e64cfc10174"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.2"

[[constraint]]
  name = "github.com/aliyun/aliyun-oss-go-sdk"
  version = "1.9.4"

[[override]]
name = "gopkg.in/fsnotify.v1"
source = "https://github.com/fsnotify/fsnotify.git"

[[override]]
name = "github.com/ugorji/go"
revision = "b4c50a2b199d93b13dc15e78929cfb23bfdf21ab"